# Travis can building for Linux (Ubuntu 14.04 x64) and OS X (El Capitan)
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: generic

    # To maximise compatibility pick earliest image, 10.9 to be removed on 20/01/2017
    - os: osx
      osx_image: beta-xcode6.1
      sudo: required
      language: generic

before_install:
  # OS and default Python info
  - uname -a
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sw_vers; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then python3 -c "import sys; print(sys.executable)"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo python3 -c "import sys; print(sys.executable)"; fi

install:
  # Python 3 and pip 3 installation are OS dependent
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then bash package/install_osx.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then bash package/install_linux.sh; fi

  # Install Mu dependencies (PyQt & QScintilla will be absorbed in requirements.txt once ready)
  - sudo pip3 install -r requirements.txt
  - sudo pip3 install PyQt5
  - sudo pip3 install QScintilla

  # Install packaging dependencies, macOS depends on update not yet released https://github.com/pyinstaller/pyinstaller/pull/1965
  - sudo pip3 install git+git://github.com/pyinstaller/pyinstaller.git@483c819d6a256b58db6740696a901bd41c313f0c

  # Check everything was correctly installed
  - echo $PATH
  - python3 --version
  - python3 -c "import struct; print(struct.calcsize('P') * 8)"
  - python3 -c "import sys; print(sys.executable)"
  - pip3 --version
  - sudo pip3 --version
  - pip3 freeze
  - python3 -c "import PyQt5"
  - python3 -c "import PyQt5.Qsci"

script:
  # Run the tests, at the moment there is a segmentation fault on Linux, this will go away with Py3.5
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then make check; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then make clean; fi

  # Package it
  - pyinstaller package/pyinstaller.spec
  - du -sk dist/
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then mv dist/mu dist/mu_$(date '+%Y-%m-%d_%H_%M')_${TRAVIS_BRANCH}_${TRAVIS_COMMIT:0:7}.bin; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cd dist && zip --symlinks -r mu_$(date '+%Y-%m-%d_%H_%M')_${TRAVIS_BRANCH}_${TRAVIS_COMMIT:0:7}.zip mu.app && rm -r mu.app && rm mu && cd ..; fi

# Deploy the build version in an S3 bucket
deploy:
  provider: s3
  access_key_id: AKIAJOLFMO6LWP5Y656Q
  secret_access_key:
    secure: huoABM0KwkZAk5+IfGJqInAVaTIpuIlKuPR27F3CrJUFlXy+h83z+Yzx2jiA0Hgb5r3Wst8BU3LLRanFO5iXvJ/xHHe3xohqXuwitPEOomhXriMrifiEHlo4bLmthfSL5fIiWbkg1jk6o3BaepCI/TmDPXOylXh6bTxRpMNjyJJPM5jQyQaeO+I3SrHkAmnCqgvT8ijTKNMktw02D8hDbbE61ZRYuN45Onuf33hQhvnnSLKSKJIpvVQMDQfMP1aplwlPscJPhjlQ8e2aSwUhInz+mS+Q/ExTnLJs7/2RDGKIAlObFel2wWVWScr0DovMy+OR47Ix9FI5oLnHUzVQ3TvF9dF6Ugjpx4RmXTaw5pAeThH6rz0yeh+fQEdSeuad1j/PCWOFLovA8BhxNQAg17XTA0gqoijwBF/KlcLqT03bKlBtt+RbCT+RrzXiFEeW0zhcnODcyWyLtNyBbQossltfE0Jp3jvpnubE93AOetUFZpQMnncQqXwj5I8g5MeCzfSyQ9bYw/vxm32kgr0i41v8i52BD9w1jhxJUKskF931BCYqoHiGYwNGjNQV7XusBi60biBoSe0grI/AsMrAgEhleY8YHpirOv45xOdl19vaDfzul2VbUbZZwVTg3uVIBAWGbgS2XbY4IXHBkJT1arQk5URNG32ikeIstZZuUCI=
  bucket: elmo-microbit-deployment
  region: ap-southeast-2
  # Keep the build artefacts around, so they can be deployed.
  skip_cleanup: true
  local-dir: dist/
  upload-dir: $TRAVIS_OS_NAME
  acl: public_read
  on:
    repo: tsukasa-au/mu
    branch: master

notifications:
  email:
    on_success: change
    on_failure: change
